**ANN**


Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

Importing dataset

In [14]:


# Retype the path manually (ensure there are no hidden characters)
dataset = pd.read_csv("C:\\Users\\ompan\\OneDrive\\Desktop\\Churn_Modelling.csv")



X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [15]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [16]:
print(Y)

[1 0 1 ... 1 1 0]


Encoding categorical data (Label Encoding the gender column)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [18]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the geography column

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [20]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the training set and test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Building the ANN
Initializing the ANN

In [23]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [26]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training the ANN
Compiling the ANN

In [27]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)


Epoch 1/100


250/250 [==============================] - 1s 966us/step - loss: 0.7249 - accuracy: 0.5665
Epoch 2/100
250/250 [==============================] - 0s 839us/step - loss: 0.5219 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 907us/step - loss: 0.4789 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 0s 871us/step - loss: 0.4553 - accuracy: 0.7993
Epoch 5/100
250/250 [==============================] - 0s 943us/step - loss: 0.4278 - accuracy: 0.8115
Epoch 6/100
250/250 [==============================] - 0s 896us/step - loss: 0.4037 - accuracy: 0.8221
Epoch 7/100
250/250 [==============================] - 0s 917us/step - loss: 0.3888 - accuracy: 0.8238
Epoch 8/100
250/250 [==============================] - 0s 868us/step - loss: 0.3784 - accuracy: 0.8290
Epoch 9/100
250/250 [==============================] - 0s 905us/step - loss: 0.3717 - accuracy: 0.8316
Epoch 10/100
250/250 [==============================] - 0s 925us/step 

250/250 [==============================] - 0s 844us/step - loss: 0.3313 - accuracy: 0.8630
Epoch 74/100
250/250 [==============================] - 0s 868us/step - loss: 0.3313 - accuracy: 0.8627
Epoch 75/100
250/250 [==============================] - 0s 850us/step - loss: 0.3307 - accuracy: 0.8630
Epoch 76/100
250/250 [==============================] - 0s 868us/step - loss: 0.3311 - accuracy: 0.8631
Epoch 77/100
250/250 [==============================] - 0s 881us/step - loss: 0.3308 - accuracy: 0.8625
Epoch 78/100
250/250 [==============================] - 0s 833us/step - loss: 0.3312 - accuracy: 0.8625
Epoch 79/100
250/250 [==============================] - 0s 879us/step - loss: 0.3308 - accuracy: 0.8611
Epoch 80/100
250/250 [==============================] - 0s 888us/step - loss: 0.3307 - accuracy: 0.8619
Epoch 81/100
250/250 [==============================] - 0s 878us/step - loss: 0.3306 - accuracy: 0.8631
Epoch 82/100
250/250 [==============================] - 0s 909us/step - loss:

Predicting the test set result

In [28]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 808us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1511   84]
 [ 198  207]]


0.859